/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */

export type AssetsControllerFindAllType = typeof AssetsControllerFindAllType[keyof typeof AssetsControllerFindAllType];


export const AssetsControllerFindAllType = {
  BGM: 'BGM',
  SFX: 'SFX',
  BACKGROUND: 'BACKGROUND',
  OVERLAY: 'OVERLAY',
  FONT: 'FONT',
} as const;
