/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */
import type { AssetsControllerFindAllType } from './assetsControllerFindAllType';

export type AssetsControllerFindAllParams = {
type?: AssetsControllerFindAllType;
};
