/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */

export type CreateAssetDtoType = typeof CreateAssetDtoType[keyof typeof CreateAssetDtoType];


export const CreateAssetDtoType = {
  BGM: 'BGM',
  SFX: 'SFX',
  BACKGROUND: 'BACKGROUND',
  OVERLAY: 'OVERLAY',
  FONT: 'FONT',
} as const;
