/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */

export interface CreateCharacterReferenceDto {
  /** 이미지 URL */
  imageUrl: string;
  /** 레퍼런스 타입 */
  type: string;
  /** 이미지 프롬프트 */
  prompt?: string;
}
