/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */
import type { CreateAssetDtoMetadata } from './createAssetDtoMetadata';
import type { CreateAssetDtoType } from './createAssetDtoType';

export interface CreateAssetDto {
  type: CreateAssetDtoType;
  title: string;
  /** S3/CDN URL */
  url: string;
  tags?: string[];
  metadata?: CreateAssetDtoMetadata;
}
