/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */

export interface CreateEpisodeDto {
  episodeNumber: number;
  title: string;
  description?: string;
  extraPrompt?: string;
}
