/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */

export interface CreateCharacterDto {
  name: string;
  description?: string;
  age?: number;
  gender?: string;
  personality?: string;
  /** 이미지 생성용 기본 프롬프트 */
  basePrompt?: string;
  /** 음성 타입 (OpenAI voice ID: alloy, ash, coral, echo, fable, nova, onyx, sage, shimmer) */
  voiceType?: string;
  /** ElevenLabs 음성 타입 (adam, arnold, antoni, elli, domi, rachel, bella, josh, sam) */
  elevenLabsVoiceType?: string;
  /** Typecast actor_id (Typecast 대시보드에서 확인) */
  typecastVoiceType?: string;
}
