/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */

export interface GenerateTtsDto {
  /** 사용할 음성 ID (OpenAI voice name) */
  voiceId?: string;
  /** 특정 캐릭터 ID */
  characterId?: string;
  /** 재생 속도 */
  speed?: number;
}
