/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */

export interface GenerateSceneImageDto {
  /** 추가 이미지 프롬프트 */
  prompt?: string;
  negativePrompt?: string;
  style?: string;
  width?: number;
  height?: number;
}
