/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */

/**
 * 화면 비율 (쇼츠: 9:16)
 */
export type ImageToVideoDtoAspectRatio = typeof ImageToVideoDtoAspectRatio[keyof typeof ImageToVideoDtoAspectRatio];


export const ImageToVideoDtoAspectRatio = {
  '16:9': '16:9',
  '9:16': '9:16',
  '1:1': '1:1',
} as const;
