/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */

/**
 * 생성 영상 길이(초)
 */
export type ImageToVideoDtoDuration = typeof ImageToVideoDtoDuration[keyof typeof ImageToVideoDtoDuration];


export const ImageToVideoDtoDuration = {
  NUMBER_5: 5,
  NUMBER_10: 10,
} as const;
