/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */
import type { ImageToVideoDtoAspectRatio } from './imageToVideoDtoAspectRatio';
import type { ImageToVideoDtoDuration } from './imageToVideoDtoDuration';

export interface ImageToVideoDto {
  /** 움직임 묘사 프롬프트 (예: "캐릭터가 손짓하며 설명하는 동작") */
  motionPrompt?: string;
  /** 생성 영상 길이(초) */
  duration?: ImageToVideoDtoDuration;
  /** 화면 비율 (쇼츠: 9:16) */
  aspectRatio?: ImageToVideoDtoAspectRatio;
}
