/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */
import type { RenderClipDtoMotionEffect } from './renderClipDtoMotionEffect';

export interface RenderClipDto {
  /** 모션 효과 (zoom_in/zoom_out/pan_right/pan_left/ken_burns/none/shake/flash/impact_zoom/speed_pan/strobe) */
  motionEffect?: RenderClipDtoMotionEffect;
}
