/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */

/**
 * 모션 효과 (zoom_in/zoom_out/pan_right/pan_left/ken_burns/none/shake/flash/impact_zoom/speed_pan/strobe)
 */
export type RenderClipDtoMotionEffect = typeof RenderClipDtoMotionEffect[keyof typeof RenderClipDtoMotionEffect];


export const RenderClipDtoMotionEffect = {
  zoom_in: 'zoom_in',
  zoom_out: 'zoom_out',
  pan_right: 'pan_right',
  pan_left: 'pan_left',
  ken_burns: 'ken_burns',
  none: 'none',
  shake: 'shake',
  flash: 'flash',
  impact_zoom: 'impact_zoom',
  speed_pan: 'speed_pan',
  strobe: 'strobe',
} as const;
