/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */
import type { UpdateSceneDtoStatus } from './updateSceneDtoStatus';

export interface UpdateSceneDto {
  title?: string;
  narration?: string;
  duration?: number;
  emotion?: string;
  background?: string;
  cameraDirection?: string;
  dialogueJson?: string;
  status?: UpdateSceneDtoStatus;
}
