/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */

export interface UpdateSeriesDto {
  title?: string;
  description?: string;
  stylePrompt?: string;
  thumbnail?: string;
}
