/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */
import type { UpdateEpisodeDtoStatus } from './updateEpisodeDtoStatus';

export interface UpdateEpisodeDto {
  title?: string;
  description?: string;
  status?: UpdateEpisodeDtoStatus;
  thumbnail?: string;
}
