/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */

export type UpdateScriptDtoStatus = typeof UpdateScriptDtoStatus[keyof typeof UpdateScriptDtoStatus];


export const UpdateScriptDtoStatus = {
  DRAFT: 'DRAFT',
  GENERATING: 'GENERATING',
  READY: 'READY',
  APPROVED: 'APPROVED',
  FAILED: 'FAILED',
} as const;
