/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */
import type { UpdateScriptDtoStatus } from './updateScriptDtoStatus';

export interface UpdateScriptDto {
  content?: string;
  summary?: string;
  status?: UpdateScriptDtoStatus;
}
