/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */

export type UpdateSceneDtoStatus = typeof UpdateSceneDtoStatus[keyof typeof UpdateSceneDtoStatus];


export const UpdateSceneDtoStatus = {
  PENDING: 'PENDING',
  IMAGE_GENERATING: 'IMAGE_GENERATING',
  IMAGE_READY: 'IMAGE_READY',
  VOICE_GENERATING: 'VOICE_GENERATING',
  VOICE_READY: 'VOICE_READY',
  RENDERING: 'RENDERING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
} as const;
