/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Video Render API
 * AI Animation Studio API
 * OpenAPI spec version: 1.0
 */

export type UpdateEpisodeDtoStatus = typeof UpdateEpisodeDtoStatus[keyof typeof UpdateEpisodeDtoStatus];


export const UpdateEpisodeDtoStatus = {
  DRAFT: 'DRAFT',
  SCRIPT_READY: 'SCRIPT_READY',
  SCENE_READY: 'SCENE_READY',
  VOICE_READY: 'VOICE_READY',
  RENDERING: 'RENDERING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
} as const;
